bbs/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# from .views import ContactFormView, ContactResultView

app_name = 'bbs'

urlpatterns = [
	path('',views.index, name='index'),
    path('contact/', views.contact_form, name='contact_form'),
    path('contact/complete/', views.complete, name='complete'),
	path('<slug:slug>/',views.detail, name='detail'),
	path('category/<str:category>/',views.category, name='category'),
	path('tag/<str:tag>/',views.tag, name='tag'),
	path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
]

myapp/urls.py
from django.urls import include, path
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from .sitemaps import (
    BlogPostSitemap,StaticViewSitemap
)
from django.views.generic import TemplateView

sitemaps = {
    'blog': BlogPostSitemap,
    'static': StaticViewSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bbs.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
	path('sw.js', (TemplateView.as_view(template_name="sw.js",content_type='application/javascript', )), name='sw.js'),
]

# 開発環境下のみ設定
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bbs/models.py
# from turtle import title
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

class Category(models.Model):
  name = models.CharField('カテゴリー', max_length=50)
  slug = models.SlugField('スラッグ', unique=True, null=True)

  def __str__(self):
      return self.name

class Tag(models.Model):
  name = models.CharField('タグ', max_length=50)
  slug = models.SlugField('スラッグ', unique=True, null=True)

  def __str__(self):
      return self.name

class Article(models.Model):
  title = models.CharField('タイトル', max_length=200, null=True)
  description = models.CharField('説明', max_length=500, null=True)
  content = models.TextField('テキスト')
  article_body = models.CharField('プレーンテキスト', max_length=3000, null=True)
  created_at = models.DateField('作成日', auto_now_add=True)
  updated_at = models.DateField('更新日', auto_now=True)
  slug = models.SlugField('スラッグ',blank=True, unique=False, max_length=255)
  category = models.ForeignKey(
                Category, verbose_name='カテゴリー',
                on_delete=models.PROTECT
              )
  tag = models.ManyToManyField(Tag, verbose_name='タグ')
  thumbnail_image_name = models.CharField('画像用タグ名称', max_length=200, null=True)

  def __str__(self):
    return self.title

  def get_absolute_url(self):
    return reverse('detail', args=[self.slug])

  def save(self, *args, **kwargs):
    if not self.slug:
        self.slug = slugify(self.title)
    super(Article, self).save(*args, **kwargs)

bbs/forms.py
from django import forms

class ContactForm(forms.Form):
	subject = forms.CharField(max_length=100,
            widget=forms.TextInput(
            attrs={'placeholder':'Subject', 'class':'p-contact__input'}))
	sender = forms.EmailField(widget=forms.TextInput(
            attrs={'placeholder':'E-mail', 'class':'p-contact__input'}))
	message = forms.CharField(widget=forms.Textarea(
            attrs={'placeholder':'Message', 'class':'p-contact__textarea'}))
	myself = forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={'id':'box', 'class':'p-contact__checkbox'}))

bbs/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render,get_object_or_404
from bbs.models import Category, Article, Tag
from django.views.generic import TemplateView
import os
from dotenv import load_dotenv
load_dotenv()
GOOGLE_API_SSID = os.getenv("GOOGLE_API_SSID")
GOOGLE_API_JSON = os.getenv("GOOGLE_API_JSON")
IMG_PATH = os.getenv("IMG_PATH")
EXCEL_PATH = os.getenv("EXCEL_PATH")

from django.shortcuts import render, redirect
from .forms import ContactForm
from django.http import HttpResponse
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt , pandas as pd

def paginate_queryset(request, queryset, count):
	paginator = Paginator(queryset, count)
	page = request.GET.get('page')
	try:
		page_obj = paginator.page(page)
	except PageNotAnInteger:
		page_obj = paginator.page(1)
	except EmptyPage:
		page_obj = paginator.page(paginator.num_pages)
	return page_obj

def index(request):
	articles = Article.objects.order_by('-id')
	page_obj = paginate_queryset(request, articles, 6)
	return render(request,'bbs/index.html',{'articles': page_obj.object_list,'page_obj': page_obj})

def category(request, category):
	category = Category.objects.get(name=category)
	articles = Article.objects.order_by('-id').filter(category=category)
	page_obj = paginate_queryset(request, articles, 6)
	return render(request, 'bbs/list.html',{'category': category, 'articles': page_obj.object_list,'page_obj': page_obj })

def tag(request, tag):
	tag = Tag.objects.get(name=tag)
	articles = Article.objects.order_by('-id').filter(tag=tag)
	page_obj = paginate_queryset(request, articles, 6)
	return render(request, 'bbs/list.html',{'tag': tag, 'articles': page_obj.object_list,'page_obj': page_obj })

from datetime import datetime

def detail(request, slug):
	entries = Article.objects.order_by('-id')[:3]
	article = get_object_or_404(Article, slug=slug)

	excel_file_path = EXCEL_PATH + 'weight.xlsx'
	workbook = pd.ExcelFile(excel_file_path)
	worksheet = workbook.parse('weight')

	col_values = worksheet.iloc[:, 0].dropna().values

	pngDate = str(col_values[-1])
	weight_png_date = pd.to_datetime(pngDate).date()

	article_updated_at = article.updated_at


	current_year = datetime.now().year
	formatted_date = f"{current_year}/{weight_png_date.month}/{weight_png_date.day}"
	weight_png_date = datetime.strptime(formatted_date, '%Y/%m/%d').date()


	with plt.style.context('Solarize_Light2'):
		plt.rcParams["figure.figsize"] = (12, 6)
		plt.ylim(66, 84)

		plt.plot(worksheet['date'], worksheet['weight'], marker='o', color='#4e3b2f')
		plt.title('Weight Graph')
		plt.xlabel('Date')
		plt.ylabel('Weight')

		plt.xticks(worksheet['date'], rotation=45, ha='right')

		plt.grid(True)
		plt.tight_layout()
		plt.savefig(IMG_PATH + 'weight.png')

	if article.slug == "fitness":
		if article_updated_at > weight_png_date:
			latest_date = article_updated_at
		else:
			latest_date = weight_png_date
	else:
		latest_date = article_updated_at

	params = {
		'article': article,
		'entries': entries,
		'pngDate': pngDate,
		'latest_date': latest_date,
	}

	return render(request,'bbs/detail.html', params)


def complete(request):
	entries = Article.objects.order_by('-id')[:3]
	article = Article.objects.order_by('-id')
	return render(request, 'bbs/complete.html', {'article':article,'entries': entries})

def contact_form(request):
	entries = Article.objects.order_by('-id')[:3]
	article = Article.objects.order_by('-id')
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			subject = form.cleaned_data['subject']
			message = form.cleaned_data['message']
			sender = form.cleaned_data['sender']
			myself = form.cleaned_data['myself']
			recipients = [settings.EMAIL_HOST_USER]
			if myself:
				recipients.append(sender)
			try:
				send_mail(subject, message, sender, recipients)
			except BadHeaderError:
				return HttpResponse('Invalid header found')
			return redirect('bbs:complete')
	else:
		form = ContactForm()
	return render(request, 'bbs/contact.html', {'form': form,'article':article,'entries': entries})

bbs/templates/bbs/complete.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, minimum-scale=1">
<title>Send completely | TECH BLOG</title>
<meta name="description" content="Send completely.Thanks for your message. Depending on the content, I may not be able to reply. Also, replies may be delayed. I apologize in advance. I am sorry.">
<link rel="stylesheet" href="/static/css/contact.css?{% now 'U' %}">
<link rel="preconnect" href="https://ajax.googleapis.com">
<link rel="dns-prefetch" href="https://ajax.googleapis.com">
<link rel="canonical" href="https://sohtani.pythonanywhere.com/contact/complete/">
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
<link rel="manifest" href="/static/json/manifest.json">
<script>
if ('serviceWorker' in navigator) {
	window.addEventListener('load', function() {
		navigator.serviceWorker.register('../../sw.js').then(function() { console.log('Service Worker Registered');
		},function(err) {
		console.log('ServiceWorker registration failed: ', err);
		});
	});
}
</script>
</head>
<body id="top">
<div class="f-wrapper">
{% include './include/l_header.html' %}
<main class="l-main">
	<div class="l-contents">
		<div class="l-container">
		  <p class="l-contents__title">CONTACT</p>
		  <div class="l-container__inner">
			<article class="l-article__contact">
					<div class="p-complete">
						<h1 class="p-complete__h1 en">Send completely</h1>
						<h2 class="p-complete__h2">Thanks for your message.<br>Depending on the content, I may not be able to reply.<br>Also, replies may be delayed.<br>I apologize in advance. I'm sorry.</h2>
					</div>
			</article>
			{% include './include/l_aside.html' %}
		  </div>
			<ol class="c-breadcrumbs">
				<li class="c-breadcrumbs__item">
					<a href="{% url 'bbs:index' %}" title="home">
						<i class="icon-home3"></i>
					</a>
				</li>
				<li class="c-breadcrumbs__item">
					<a href="{% url 'bbs:contact_form' %}">
						CONTACT
					</a>
				</li>
				<li class="c-breadcrumbs__item">Send completely</li>
			</ol>
		</div>
	</div>
	{% include './include/l_author.html' %}
</main>
{% include './include/l_footer.html' %}
</div>
<script defer src="/static/js/main.js?{% now 'U' %}"></script>
<script type="application/ld+json">[{"@context": "https://schema.org","@type": "SiteNavigationElement","hasPart": [{"@type": "WebPage","name": "HOME","url": "https://sohtani.pythonanywhere.com/"},{"@type": "CollectionPage","name": "PYTHON","url": "https://sohtani.pythonanywhere.com/category/python/"},{"@type": "CollectionPage","name": "TOOL","url": "https://sohtani.pythonanywhere.com/category/tool/"},{"@type": "WebPage","name": "FITNESS","url": "https://sohtani.pythonanywhere.com/fitness/"},{"@type": "ContactPage","name": "CONTACT","url": "https://sohtani.pythonanywhere.com/contact/"},{"@type": "WebPage","name": "GitHub","url": "https://github.com/shim369"}]}]</script>
<!-- Google tag (gtag.js) -->
<script defer src="https://www.googletagmanager.com/gtag/js?id=G-C4QW4L4G4R"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-C4QW4L4G4R');
</script>
</body>
</html>

bbs/templates/bbs/contact.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, minimum-scale=1">
<title>Contact | TECH BLOG</title>
<meta name="description" content="Depending on the content, I may not be able to reply. Also, replies may be delayed. I apologize in advance. I am sorry.">
<link rel="stylesheet" href="/static/css/contact.css?{% now 'U' %}">
<link rel="canonical" href="https://sohtani.pythonanywhere.com/contact/">
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
<link rel="manifest" href="/static/json/manifest.json">
<script>
if ('serviceWorker' in navigator) {
	window.addEventListener('load', function() {
		navigator.serviceWorker.register('../sw.js').then(function() { console.log('Service Worker Registered');
		},function(err) {
		console.log('ServiceWorker registration failed: ', err);
		});
	});
}
</script>
</head>
<body id="top">
<div class="l-wrapper">
{% include './include/l_header.html' %}
<main class="l-main">
	<div class="l-contents">
		<div class="l-container">
		  <p class="l-contents__title">CONTACT</p>
		  <div class="l-container__inner">
			<article class="l-article__contact">
				<div class="p-contact">
				<form class="p-contact__form" action="{% url 'bbs:contact_form' %}" method="post">
				{% csrf_token %}
				{{ form.subject }}
				{{ form.sender }}
				{{ form.message }}
				{{ form.myself }}
				<label for="box">Receive the same</label>
				<div class="p-contact__text">
					<h1 class="p-contact__h1">Depending on the content, I may not be able to reply.<br>Also, replies may be delayed. I apologize in advance. I'm sorry.</h1>
					<h2 class="p-contact__h2">Did you check before sending?</h2>
				</div>
				<button id="submit" class="c-button__submit" type="submit">SEND</button>
				</form>
				</div>
			</article>
			{% include './include/l_aside.html' %}
		  </div>
			<ol class="c-breadcrumbs">
				<li class="c-breadcrumbs__item">
					<a href="{% url 'bbs:index' %}" title="home">
						<i class="icon-home3"></i>
					</a>
				</li>
				<li class="c-breadcrumbs__item">contact</li>
			</ol>
		</div>
	</div>
	{% include './include/l_author.html' %}
</main>
{% include './include/l_footer.html' %}
</div>
<script defer src="/static/js/main.js?{% now 'U' %}"></script>
<script type="application/ld+json">[{"@context": "https://schema.org","@type": "SiteNavigationElement","hasPart": [{"@type": "WebPage","name": "HOME","url": "https://sohtani.pythonanywhere.com/"},{"@type": "CollectionPage","name": "PYTHON","url": "https://sohtani.pythonanywhere.com/category/python/"},{"@type": "CollectionPage","name": "TOOL","url": "https://sohtani.pythonanywhere.com/category/tool/"},{"@type": "WebPage","name": "FITNESS","url": "https://sohtani.pythonanywhere.com/fitness/"},{"@type": "ContactPage","name": "CONTACT","url": "https://sohtani.pythonanywhere.com/contact/"},{"@type": "WebPage","name": "GitHub","url": "https://github.com/shim369"}]}]</script>
<!-- Google tag (gtag.js) -->
<script defer src="https://www.googletagmanager.com/gtag/js?id=G-C4QW4L4G4R"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-C4QW4L4G4R');
</script>
</body>
</html>

bbs/templates/bbs/include/c_card.html
<div class="c-cards">
{% for article in articles %}
<div class="c-card">
	<a class="c-card__link" href="{% url 'bbs:detail' article.slug %}" title="{{ article.title }}">
		<div class="c-card__img">
			<picture>
				<source srcset="/media/{{ article.thumbnail_image_name }}.webp" type="image/webp">
				<img src="/media/{{ article.thumbnail_image_name }}.jpg" width="309" height="160" alt="{{ article.thumbnail_image_name }}">
			</picture>
		</div>
		<div class="c-card__text">
			<div class="c-card__category">READ</div>
			<h2 class="c-card__title">{{ article.title | truncatechars:86 }}</h2>
			<time class="c-card__time" datetime="{{ article.created_at|date:'Y-m-d' }}"><i class="icon-clock2"></i>{{ article.created_at|date:"Y/m/d" }}</time>
		</div>
	</a>
</div>
{% endfor %}
</div>

bbs/templates/bbs/include/c_pagination.html
<ul class="c-pagination">
	{% if page_obj.has_previous %}
		<li class="c-pagination__item">
		<a class="c-pagination__link" href="?page={{ page_obj.previous_page_number }}">PREV</a>
		</li>
	{% endif %}

	{% for num in page_obj.paginator.page_range %}
		{% if page_obj.number == num %}
		<li class="c-pagination__item">
		<a href="?page={{ num }}" class="c-pagination__link is-active"><span>{{ num }}</span></a>
		</li>
		{% else %}
		<li class="c-pagination__item">
			<a href="?page={{ num }}" class="c-pagination__link "><span>{{ num }}</span></a>
		</li>
		{% endif %}
	{% endfor %}

	{% if page_obj.has_next %}
		<li class="c-pagination__item">
			<a class="c-pagination__link" href="?page={{ page_obj.next_page_number }}">NEXT</a>
		</li>
	{% endif %}
</ul>

bbs/templates/bbs/include/l_aside.html
<aside class="l-aside">{% if article %}
	<h3 class="l-aside__title">WHAT'S NEW</h3>
	<ul class="l-aside__wn-list">{% for article in entries %}
	<li class="l-aside__wn-list__item">
		<a class="l-aside__wn-list__link" href="{% url 'bbs:detail' article.slug %}">
			<picture class="l-aside__wn-list__thumbnail">
				<source srcset="/media/{{ article.thumbnail_image_name }}.webp" type="image/webp" width="123" height="82">
				<img src="/media/{{ article.thumbnail_image_name }}.jpg" width="123" height="82" alt="">
			</picture>
			<div class="l-aside__wn-list__text">
				<h4 class="l-aside__wn-list__h4">{{ article.title }}</h4>
				<time class="l-aside__wn-list__time" datetime="{{ article.created_at|date:'Y-m-d' }}"><i class="icon-clock2"></i>{{ article.created_at|date:"Y/m/d" }}</time>
			</div>
		</a>
	</li>{% endfor %}
	</ul>{% endif %}
	{% if articles or article %}<h3 class="l-aside__title">CATEGORY</h3>
	<ul class="l-aside__category-list">{% for category in category_list %}<li class="l-aside__category-list__item"><a class="l-aside__category-list__link" href="{% url 'bbs:category' category %}">{{ category.name }}</a></li>{% endfor %}</ul>{% endif %}
	{% if articles or article %}<h3 class="l-aside__title">TAG</h3>
	<ul class="l-aside__tag-list">{% for tag in tag_list %}<li class="l-aside__tag-list__item"><a class="l-aside__tag-list__link" href="{% url 'bbs:tag' tag %}">{{ tag.name }}</a></li>{% endfor %}</ul>{% endif %}
</aside>

bbs/templates/bbs/include/l_author.html
<div class="l-author">
	<div class="l-author__container">
	<p class="l-author__title">AUTHOR</p>
	<div class="l-author__inner">
		<div class="l-author__profile">
			<picture>
				<source srcset="/media/author.webp" type="image/webp" width="100" height="100">
				<img src="/media/author.jpg" width="100" height="100" alt="">
			</picture>
			<p class="l-author__name"><a href="https://github.com/shim369" target="_blank">S Ohtani</a></p>
	 	</div>
		<p class="l-author__intro">Almost 10 years have passed since I started learning web development. Learning web development has made my life more fulfilling. This is because the greatest benefit that can be obtained in the process of learning web development is that when you encounter difficulties, you acquire the attitude of actively searching for information to solve them on your own. And just as I learned a lot from the knowledge of my predecessors, I hope that by disseminating information in English, it will reach people around the world who want to learn web development. life is very short. I would be very happy if I could add even a little bit to your life by my outputting what I learned every day. Maybe the information is incorrect or outdated at times. I'll update when I find out.</p>
	</div>
	</div>
</div>

bbs/templates/bbs/include/l_footer.html
<footer class="l-footer">
	<!-- <div class="l-footer__page-top"><a href="#top" title="top"><i class="icon-eject"></i></a></div> -->
	<p class="l-footer__copyright"><em>TECH BLOG©2022</em></p>
</footer>

bbs/templates/bbs/include/l_header.html
<header class="l-header">
	<div class="l-header__container">
		<div class="l-header__left">
			<p class="l-header__logo">
				<a href="{% url 'bbs:index' %}">
					<img src="/media/logo.svg" width="234" height="30" alt="TECH BLOG">
				</a>
			</p>
			<nav class="l-header__nav">
				<ul class="l-header__list">
					{% if articles or article %}{% for category in category_list %}<li class="l-header__item"><a class="l-header__link" href="{% url 'bbs:category' category %}">{{ category.name }}</a></li>{% endfor %}{% endif %}
				</ul>
			</nav>
		</div>
		<ul class="l-header__icons">
			<li class="l-header__icons__item">
				<a class="l-header__icons__link" href="/fitness/" title="fitness">
					<i class="icon-fitness"></i>
				</a>
			</li>
			<li class="l-header__icons__item">
				<a class="l-header__icons__link" href="{% url 'bbs:contact_form' %}" title="contact">
					<i class="icon-mail4"></i>
				</a>
			</li>
			<li class="l-header__icons__item">
					<a class="l-header__icons__link" href="https://github.com/shim369" target="_blank" title="github">
						<i class="icon-github"></i>
				</a>
			</li>
		<!--<li class="l-header__icons__item">
				<a class="l-header__icons__link" href="" target="_blank" itemprop="url">
						<i class="icon-instagram"></i>
				</a>
			</li> -->
		</ul>
		<div class="l-header__sp-nav">
			<div class="l-header__menu-btn">
				<span data-txt-open="M" data-txt-close="C"></span>
				<span data-txt-open="E" data-txt-close="L"></span>
				<span data-txt-open="N" data-txt-close="O"></span>
				<span data-txt-open="U" data-txt-close="S"></span>
				<span data-txt-close="E"></span>
			</div>
			<nav class="l-header__menu">
			</nav>
		</div>
	</div>
</header>

bbs/templates/bbs/list.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, minimum-scale=1">
<link rel="stylesheet" href="/static/css/index.css?{% now 'U' %}">
<title>{% if category %}{{ category.slug }}{% endif %}{% if tag %}{{ tag.slug }}{% endif %} | TECH BLOG</title>
<meta property="og:title" content="TECH BLOG">
<meta property="og:type" content="article">
<meta property="og:description" content="TECH BLOG is a blog that publishes web development and a part of life.In web development, Python, Django, Figma are the main categories.">
<meta property="og:image" content="https://sohtani.pythonanywhere.com/media/{% if category %}{{ category.name }}{% endif %}{% if tag %}{{ tag.name }}{% endif %}.jpg">
<meta property="og:url" content="https://sohtani.pythonanywhere.com/{% if category %}category{% endif %}{% if tag %}tag{% endif %}/{% if category %}{{ category.name }}{% endif %}{% if tag %}{{ tag.name }}{% endif %}/">
<meta property="og:site_name" content="TECH BLOG">
<meta property="og:locale" content="en">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="TECH BLOG">
<meta name="twitter:title" content="TECH BLOG">
<meta name="twitter:description" content="TECH BLOG is a blog that publishes web development and a part of life.In web development, Python, Django, Figma are the main categories.">
<meta name="twitter:image" content="https://sohtani.pythonanywhere.com/media/og-image.png">
<meta name="twitter:url" content="https://sohtani.pythonanywhere.com/">
<meta name="description" content="{% if category %}{{ category.name }}{% endif %} | TECH BLOG is a blog that publishes web development and a part of life.In web development, Python, Django, Figma are the main categories.">
<meta name="theme-color" content="#161719">
<link rel="preconnect" href="https://www.googletagmanager.com">
<link rel="dns-prefetch" href="https://www.googletagmanager.com">
<link rel="apple-touch-icon" href="/media/icon-s.png">
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
<link rel="manifest" href="/static/json/manifest.json">
<link rel="canonical" href="https://sohtani.pythonanywhere.com/{% if category %}category{% endif %}{% if tag %}tag{% endif %}/{% if category %}{{ category.name }}{% endif %}{% if tag %}{{ tag.name }}{% endif %}/">
<script>
if ('serviceWorker' in navigator) {
	window.addEventListener('load', function() {
		navigator.serviceWorker.register('../../sw.js').then(function() { console.log('Service Worker Registered');
		},function(err) {
		console.log('ServiceWorker registration failed: ', err);
		});
	});
}
</script>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-C4QW4L4G4R"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-C4QW4L4G4R');
</script>
</head>
<body id="top">
<div class="l-wrapper">
{% include './include/l_header.html' %}
<main class="l-main">
    <div class="l-contents">
      <div class="l-container">
        <p class="l-contents__title">{% if category %}{{ category.name }}{% endif %}{% if tag %}{{ tag.name }}{% endif %}</p>
        <div class="l-container__inner">
        <article class="l-article u-bg-none">
			{% include './include/c_card.html' %}
			{% include './include/c_pagination.html' %}
        </article>
        {% include './include/l_aside.html' %}
      </div>

		<ol class="c-breadcrumbs">
			<li class="c-breadcrumbs__item">
				<a href="{% url 'bbs:index' %}" title="home">
					<i class="icon-home3"></i>
				</a>
			</li>

			{% if category %}
			<li class="c-breadcrumbs__item">
			{{ category.name }}
			</li>
			{% endif %}

			{% if tag %}
			<li class="c-breadcrumbs__item">
			{{ tag.name }}
			</li>
			{% endif %}
		</ol>
      </div>
    </div>
    {% include './include/l_author.html' %}
</main>
{% include './include/l_footer.html' %}
</div>
<script defer src="/static/js/main.js?{% now 'U' %}"></script>
<script type="application/ld+json">[{"@context": "https://schema.org","@type": "SiteNavigationElement","hasPart": [{"@type": "WebPage","name": "HOME","url": "https://sohtani.pythonanywhere.com/"},{"@type": "CollectionPage","name": "PYTHON","url": "https://sohtani.pythonanywhere.com/category/python/"},{"@type": "CollectionPage","name": "TOOL","url": "https://sohtani.pythonanywhere.com/category/tool/"},{"@type": "WebPage","name": "FITNESS","url": "https://sohtani.pythonanywhere.com/fitness/"},{"@type": "ContactPage","name": "CONTACT","url": "https://sohtani.pythonanywhere.com/contact/"},{"@type": "WebPage","name": "GitHub","url": "https://github.com/shim369"}]}]</script>
</body>
</html>